##
# Strip the store directory and hash prefix from a derivation output.
#
proc strip_hash {store_name} {
	set name ""
	regexp "\[a-z0-9\]\{32\}-(.*)" $store_name ignore name
	return $name
}

#
# Variables from the Nix expression.
#
set out  $env(out)
set name $env(name)
set graphical $env(graphical)
set setup $env(setup)
set platform_build $env(platformBuild)
set platform_setup $env(platformSetup)
set test_script $env(testScript)

exec mkdir -p $out/bin $out/nix-support
set hydra_build_products [ open $out/nix-support/hydra-build-products w]
set user_script [ open $out/bin/start-$name w]
puts $user_script "#!$env(expect)/bin/expect"
puts $user_script "source $setup"

#
# Open a logfile.
#
log_file $out/log
# this comes out with the execute bit set for some reason
exec chmod -x $out/log
puts $hydra_build_products "report testlog $out/log"


#
# Run platform build and setup.
#
source $setup
source $platform_build
source $platform_setup

exec chmod +x $out/bin/start-$name

#
# Execution of run scripts
#
if {$env(automatic) == 1} { eval $test_script }
