##
# Strip the store directory and hash prefix from a derivation output.
#
proc strip_hash {store_name} {
	set name ""
	regexp "\[a-z0-9\]\{32\}-(.*)" $store_name ignore name
	return $name
}


#
# Variables from the Nix expression.
#
set out  $env(out)
set name $env(name)
set test_script $env(testScript)

exec mkdir -p $out/bin $out/nix-support
set hydra_build_products [ open $out/nix-support/hydra-build-products w]


#
# Open a logfile.
#
log_file $out/log
# this comes out with the execute bit set for some reason
exec chmod -x $out/log
puts $hydra_build_products "report testlog $out/log"

#
# Write out a script that a user can execute later.
#
set user_script_fn $out/bin/$name
set user_script_fh [ open $user_script_fn w ]
puts $user_script_fh $env(userScript)
close $user_script_fh
exec chmod +x $user_script_fn


#
# Read and execute files passed by the Nix builder.
#
foreach arg $argv { source $arg }


#
# Execution of run scripts
#
if {$env(automatic) == 1} { eval $test_script }