create_boot_directory

import_from_depot [depot_user]/src/coreutils

set app_config {
	<start name="noux" caps="500">
		<resource name="RAM" quantum="8M"/>
		<config verbose="yes">
			<fstab> <tar name="coreutils.tar" /> </fstab>
			<start name="/bin/ls"> <arg value="-Rla"/> </start>
		</config>
	</start>
}

set build_components { noux lib/libc_noux }

set boot_modules {
	libc_noux.lib.so
	noux
}

source ${genode_dir}/repos/ports/run/noux-no-fork.inc
