proc run_genode_until {{wait_for_re forever} {timeout_value 0} {running_spawn_id -1}} {
	#
	# If a running_spawn_id is specified, wait for the expected output
	#
	if {$running_spawn_id != -1} {
		wait_for_output $wait_for_re $timeout_value $running_spawn_id
		return
	}

	global qemu qemu_args disk_image
	eval "spawn $qemu $qemu_args -cpu core2duo -serial mon:stdio"
	wait_for_output $wait_for_re $timeout_value $spawn_id
}

proc is_qemu_available {} { return 1 }
