#
# \brief  Environment for executing Genode on Linux
# \author Emery Hemingway
# \date   2014-08-11
#

proc run_genode_until {{wait_for_re forever} {timeout_value 0} {running_spawn_id -1}} {
	#
	# If a running_spawn_id is specified, wait for the expected output
	#
	if {$running_spawn_id != -1} {
		wait_for_output $wait_for_re $timeout_value $running_spawn_id
		return
	}

	global image_dir spawn_id

	cd $image_dir
	spawn ./core
	wait_for_output $wait_for_re $timeout_value $spawn_id
}
