file mkdir $out/image

file link $out/image/core $env(core)/core
file link $out/image/init $env(init)/init
file link $out/image/config $config

foreach component $env(components) {
	if [file isdirectory $component] then {
		foreach file [glob $component/*] {
			set bn [file tail $file]
			file link $out/image/$bn $file
		}
	} else {
		set bn [strip_hash $component]
		file link $out/image/$b $component
	}
}

puts $user_script "source $platform_setup"
puts $user_script "cd $out/image"
puts $user_script $test_script

close $user_script

cd $out/image
