file link $out/core $env(core)/core
file link $out/init $env(init)/init
file link $out/config $env(config)

foreach component $env(components) {
	if [file isdirectory $component] then {
		foreach file [glob $component/*] {
			file link $out/[file tail $file] $file
		}
	} else {
		set basename [strip_hash $component]
		file link $out/$basename $component
	}
}

puts $user_script "source $platform_setup"
puts $user_script "cd $out"
puts $user_script $test_script

close $user_script

cd $out
