#
# \brief  RAM allocation data plotting
# \author Emery Hemingway
# \date   2017-07-27
#

set gnuplot_cmd  [check_installed gnuplot]

set datadir var/data/ram_alloc
set datafiles [glob $datadir/*.out]

#
# Spawn Gnuplot and feed it commands thru stdio
#
set timeout -1
spawn $gnuplot_cmd

send "load \"${genode_dir}/repos/gems/run/ram_alloc.dem\"\n"

set title "RAM Allocations"

send "clear\n"
foreach datafile $datafiles {
	set name [string map {_ " "} [lindex [split [lindex [split $datafile /] end] . ] 0]]
	send "set title \"$name\"\n"

	send "plot \"$datafile\" with boxes\n"
	send "\npause mouse button1 \"Press the left mouse button to continue\"\n"
}

expect "nothing"
